worker_processes 1;
events { worker_connections 1024; }
http {
    server {
        listen 8080;
        server_name _;

        location / { root /usr/local/openresty/nginx/html; index index.html; }

        # Trojan
        location /rafaeltv {
            proxy_pass http://127.0.0.1:10000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
        location /rafaeltv-hu {
            proxy_pass http://127.0.0.1:10001;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
        location /rafaeltv-xh {
            proxy_pass http://127.0.0.1:10002;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }

        # VMess
        location /vmess-rafaeltv {
            proxy_pass http://127.0.0.1:10003;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
        location /vmess-rafaeltv-hu {
            proxy_pass http://127.0.0.1:10004;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
        location /vmess-rafaeltv-xh {
            proxy_pass http://127.0.0.1:10005;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }

        # VLESS
        location /vless-rafaeltv {
            proxy_pass http://127.0.0.1:10006;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
        location /vless-rafaeltv-hu {
            proxy_pass http://127.0.0.1:10007;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
        location /vless-rafaeltv-xh {
            proxy_pass http://127.0.0.1:10008;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }

        # Shadowsocks
        location /ss-rafaeltv {
            proxy_pass http://127.0.0.1:10009;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
        location /ss-rafaeltv-hu {
            proxy_pass http://127.0.0.1:10010;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
        location /ss-rafaeltv-xh {
            proxy_pass http://127.0.0.1:10011;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
    }
}
